//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("letsshopModel", "FK_orders_products", "product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(lets.Models.product), "order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(lets.Models.order), true)]

#endregion

namespace lets.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class letsshopEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new letsshopEntities2 object using the connection string found in the 'letsshopEntities2' section of the application configuration file.
        /// </summary>
        public letsshopEntities2() : base("name=letsshopEntities2", "letsshopEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new letsshopEntities2 object.
        /// </summary>
        public letsshopEntities2(string connectionString) : base(connectionString, "letsshopEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new letsshopEntities2 object.
        /// </summary>
        public letsshopEntities2(EntityConnection connection) : base(connection, "letsshopEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<customer_contact> customer_contact
        {
            get
            {
                if ((_customer_contact == null))
                {
                    _customer_contact = base.CreateObjectSet<customer_contact>("customer_contact");
                }
                return _customer_contact;
            }
        }
        private ObjectSet<customer_contact> _customer_contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order> orders
        {
            get
            {
                if ((_orders == null))
                {
                    _orders = base.CreateObjectSet<order>("orders");
                }
                return _orders;
            }
        }
        private ObjectSet<order> _orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sub_category> sub_category
        {
            get
            {
                if ((_sub_category == null))
                {
                    _sub_category = base.CreateObjectSet<sub_category>("sub_category");
                }
                return _sub_category;
            }
        }
        private ObjectSet<sub_category> _sub_category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<view> views
        {
            get
            {
                if ((_views == null))
                {
                    _views = base.CreateObjectSet<view>("views");
                }
                return _views;
            }
        }
        private ObjectSet<view> _views;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the customer_contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocustomer_contact(customer_contact customer_contact)
        {
            base.AddObject("customer_contact", customer_contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorders(order order)
        {
            base.AddObject("orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sub_category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosub_category(sub_category sub_category)
        {
            base.AddObject("sub_category", sub_category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the views EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToviews(view view)
        {
            base.AddObject("views", view);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="email">No Metadata Documentation available.</param>
        /// <param name="contact_Number">No Metadata Documentation available.</param>
        /// <param name="gender">No Metadata Documentation available.</param>
        /// <param name="address">No Metadata Documentation available.</param>
        /// <param name="date_of_birth">No Metadata Documentation available.</param>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        /// <param name="user_type">No Metadata Documentation available.</param>
        public int spUsers(global::System.String name, global::System.String email, global::System.String contact_Number, global::System.String gender, global::System.String address, global::System.String date_of_birth, global::System.String username, global::System.String password, global::System.String user_type)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("Email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("Email", typeof(global::System.String));
            }
    
            ObjectParameter contact_NumberParameter;
            if (contact_Number != null)
            {
                contact_NumberParameter = new ObjectParameter("Contact_Number", contact_Number);
            }
            else
            {
                contact_NumberParameter = new ObjectParameter("Contact_Number", typeof(global::System.String));
            }
    
            ObjectParameter genderParameter;
            if (gender != null)
            {
                genderParameter = new ObjectParameter("Gender", gender);
            }
            else
            {
                genderParameter = new ObjectParameter("Gender", typeof(global::System.String));
            }
    
            ObjectParameter addressParameter;
            if (address != null)
            {
                addressParameter = new ObjectParameter("Address", address);
            }
            else
            {
                addressParameter = new ObjectParameter("Address", typeof(global::System.String));
            }
    
            ObjectParameter date_of_birthParameter;
            if (date_of_birth != null)
            {
                date_of_birthParameter = new ObjectParameter("Date_of_birth", date_of_birth);
            }
            else
            {
                date_of_birthParameter = new ObjectParameter("Date_of_birth", typeof(global::System.String));
            }
    
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("Username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("Username", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            ObjectParameter user_typeParameter;
            if (user_type != null)
            {
                user_typeParameter = new ObjectParameter("user_type", user_type);
            }
            else
            {
                user_typeParameter = new ObjectParameter("user_type", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spUsers", nameParameter, emailParameter, contact_NumberParameter, genderParameter, addressParameter, date_of_birthParameter, usernameParameter, passwordParameter, user_typeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> splogin(global::System.String username, global::System.String password)
        {
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("Username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("Username", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("splogin", usernameParameter, passwordParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="quantity">No Metadata Documentation available.</param>
        /// <param name="price">No Metadata Documentation available.</param>
        /// <param name="description">No Metadata Documentation available.</param>
        /// <param name="subcat_name">No Metadata Documentation available.</param>
        /// <param name="img_loc">No Metadata Documentation available.</param>
        public int spADDProduct(Nullable<global::System.Int32> quantity, Nullable<global::System.Int32> price, global::System.String description, global::System.String subcat_name, global::System.String img_loc)
        {
            ObjectParameter quantityParameter;
            if (quantity.HasValue)
            {
                quantityParameter = new ObjectParameter("quantity", quantity);
            }
            else
            {
                quantityParameter = new ObjectParameter("quantity", typeof(global::System.Int32));
            }
    
            ObjectParameter priceParameter;
            if (price.HasValue)
            {
                priceParameter = new ObjectParameter("price", price);
            }
            else
            {
                priceParameter = new ObjectParameter("price", typeof(global::System.Int32));
            }
    
            ObjectParameter descriptionParameter;
            if (description != null)
            {
                descriptionParameter = new ObjectParameter("description", description);
            }
            else
            {
                descriptionParameter = new ObjectParameter("description", typeof(global::System.String));
            }
    
            ObjectParameter subcat_nameParameter;
            if (subcat_name != null)
            {
                subcat_nameParameter = new ObjectParameter("subcat_name", subcat_name);
            }
            else
            {
                subcat_nameParameter = new ObjectParameter("subcat_name", typeof(global::System.String));
            }
    
            ObjectParameter img_locParameter;
            if (img_loc != null)
            {
                img_locParameter = new ObjectParameter("img_loc", img_loc);
            }
            else
            {
                img_locParameter = new ObjectParameter("img_loc", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spADDProduct", quantityParameter, priceParameter, descriptionParameter, subcat_nameParameter, img_locParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="product_id">No Metadata Documentation available.</param>
        /// <param name="customer_name">No Metadata Documentation available.</param>
        /// <param name="quantity">No Metadata Documentation available.</param>
        /// <param name="total_amount">No Metadata Documentation available.</param>
        public int spAddOrder(Nullable<global::System.Int32> product_id, global::System.String customer_name, Nullable<global::System.Int32> quantity, Nullable<global::System.Int32> total_amount)
        {
            ObjectParameter product_idParameter;
            if (product_id.HasValue)
            {
                product_idParameter = new ObjectParameter("product_id", product_id);
            }
            else
            {
                product_idParameter = new ObjectParameter("product_id", typeof(global::System.Int32));
            }
    
            ObjectParameter customer_nameParameter;
            if (customer_name != null)
            {
                customer_nameParameter = new ObjectParameter("customer_name", customer_name);
            }
            else
            {
                customer_nameParameter = new ObjectParameter("customer_name", typeof(global::System.String));
            }
    
            ObjectParameter quantityParameter;
            if (quantity.HasValue)
            {
                quantityParameter = new ObjectParameter("quantity", quantity);
            }
            else
            {
                quantityParameter = new ObjectParameter("quantity", typeof(global::System.Int32));
            }
    
            ObjectParameter total_amountParameter;
            if (total_amount.HasValue)
            {
                total_amountParameter = new ObjectParameter("total_amount", total_amount);
            }
            else
            {
                total_amountParameter = new ObjectParameter("total_amount", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("spAddOrder", product_idParameter, customer_nameParameter, quantityParameter, total_amountParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<sptotal_Result> sptotal()
        {
            return base.ExecuteFunction<sptotal_Result>("sptotal");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        public int spApprove(Nullable<global::System.Int32> id)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("spApprove", idParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        public int spDeleteuser(Nullable<global::System.Int32> id)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("spDeleteuser", idParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        public int spOrderemove(Nullable<global::System.Int32> id)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("spOrderemove", idParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        public int spremoveProducts(Nullable<global::System.Int32> id)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("spremoveProducts", idParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="category_id">Initial value of the category_id property.</param>
        /// <param name="category_name">Initial value of the category_name property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        public static category Createcategory(global::System.Int32 category_id, global::System.String category_name, global::System.DateTime created_date)
        {
            category category = new category();
            category.category_id = category_id;
            category.category_name = category_name;
            category.created_date = created_date;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 category_id
        {
            get
            {
                return _category_id;
            }
            set
            {
                if (_category_id != value)
                {
                    Oncategory_idChanging(value);
                    ReportPropertyChanging("category_id");
                    _category_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("category_id");
                    Oncategory_idChanged();
                }
            }
        }
        private global::System.Int32 _category_id;
        partial void Oncategory_idChanging(global::System.Int32 value);
        partial void Oncategory_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String category_name
        {
            get
            {
                return _category_name;
            }
            set
            {
                Oncategory_nameChanging(value);
                ReportPropertyChanging("category_name");
                _category_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("category_name");
                Oncategory_nameChanged();
            }
        }
        private global::System.String _category_name;
        partial void Oncategory_nameChanging(global::System.String value);
        partial void Oncategory_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="customer_contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class customer_contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new customer_contact object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstname">Initial value of the Firstname property.</param>
        /// <param name="lastname">Initial value of the Lastname property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="created_Date">Initial value of the Created_Date property.</param>
        public static customer_contact Createcustomer_contact(global::System.Int32 id, global::System.String firstname, global::System.String lastname, global::System.String email, global::System.String subject, global::System.String message, global::System.DateTime created_Date)
        {
            customer_contact customer_contact = new customer_contact();
            customer_contact.Id = id;
            customer_contact.Firstname = firstname;
            customer_contact.Lastname = lastname;
            customer_contact.Email = email;
            customer_contact.Subject = subject;
            customer_contact.Message = message;
            customer_contact.Created_Date = created_Date;
            return customer_contact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lastname
        {
            get
            {
                return _Lastname;
            }
            set
            {
                OnLastnameChanging(value);
                ReportPropertyChanging("Lastname");
                _Lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lastname");
                OnLastnameChanged();
            }
        }
        private global::System.String _Lastname;
        partial void OnLastnameChanging(global::System.String value);
        partial void OnLastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created_Date
        {
            get
            {
                return _Created_Date;
            }
            set
            {
                OnCreated_DateChanging(value);
                ReportPropertyChanging("Created_Date");
                _Created_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_Date");
                OnCreated_DateChanged();
            }
        }
        private global::System.DateTime _Created_Date;
        partial void OnCreated_DateChanging(global::System.DateTime value);
        partial void OnCreated_DateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order object.
        /// </summary>
        /// <param name="order_id">Initial value of the order_id property.</param>
        /// <param name="product_id">Initial value of the product_id property.</param>
        /// <param name="customer_name">Initial value of the customer_name property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        /// <param name="total_amount">Initial value of the total_amount property.</param>
        /// <param name="order_date">Initial value of the order_date property.</param>
        /// <param name="status">Initial value of the status property.</param>
        public static order Createorder(global::System.Int32 order_id, global::System.Int32 product_id, global::System.String customer_name, global::System.Int32 quantity, global::System.Int32 total_amount, global::System.DateTime order_date, global::System.String status)
        {
            order order = new order();
            order.order_id = order_id;
            order.product_id = product_id;
            order.customer_name = customer_name;
            order.quantity = quantity;
            order.total_amount = total_amount;
            order.order_date = order_date;
            order.status = status;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Int32 _order_id;
        partial void Onorder_idChanging(global::System.Int32 value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String customer_name
        {
            get
            {
                return _customer_name;
            }
            set
            {
                Oncustomer_nameChanging(value);
                ReportPropertyChanging("customer_name");
                _customer_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("customer_name");
                Oncustomer_nameChanged();
            }
        }
        private global::System.String _customer_name;
        partial void Oncustomer_nameChanging(global::System.String value);
        partial void Oncustomer_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.Int32 _quantity;
        partial void OnquantityChanging(global::System.Int32 value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 total_amount
        {
            get
            {
                return _total_amount;
            }
            set
            {
                Ontotal_amountChanging(value);
                ReportPropertyChanging("total_amount");
                _total_amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_amount");
                Ontotal_amountChanged();
            }
        }
        private global::System.Int32 _total_amount;
        partial void Ontotal_amountChanging(global::System.Int32 value);
        partial void Ontotal_amountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime order_date
        {
            get
            {
                return _order_date;
            }
            set
            {
                Onorder_dateChanging(value);
                ReportPropertyChanging("order_date");
                _order_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_date");
                Onorder_dateChanged();
            }
        }
        private global::System.DateTime _order_date;
        partial void Onorder_dateChanging(global::System.DateTime value);
        partial void Onorder_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("letsshopModel", "FK_orders_products", "product")]
        public product product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("letsshopModel.FK_orders_products", "product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("letsshopModel.FK_orders_products", "product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<product> productReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("letsshopModel.FK_orders_products", "product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<product>("letsshopModel.FK_orders_products", "product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="product_id">Initial value of the product_id property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="subcat_name">Initial value of the subcat_name property.</param>
        /// <param name="img_loc">Initial value of the img_loc property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        public static product Createproduct(global::System.Int32 product_id, global::System.Int32 quantity, global::System.Int32 price, global::System.String description, global::System.String subcat_name, global::System.String img_loc, global::System.DateTime created_date)
        {
            product product = new product();
            product.product_id = product_id;
            product.quantity = quantity;
            product.price = price;
            product.description = description;
            product.subcat_name = subcat_name;
            product.img_loc = img_loc;
            product.created_date = created_date;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.Int32 _quantity;
        partial void OnquantityChanging(global::System.Int32 value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Int32 _price;
        partial void OnpriceChanging(global::System.Int32 value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String subcat_name
        {
            get
            {
                return _subcat_name;
            }
            set
            {
                Onsubcat_nameChanging(value);
                ReportPropertyChanging("subcat_name");
                _subcat_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("subcat_name");
                Onsubcat_nameChanged();
            }
        }
        private global::System.String _subcat_name;
        partial void Onsubcat_nameChanging(global::System.String value);
        partial void Onsubcat_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String img_loc
        {
            get
            {
                return _img_loc;
            }
            set
            {
                Onimg_locChanging(value);
                ReportPropertyChanging("img_loc");
                _img_loc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("img_loc");
                Onimg_locChanged();
            }
        }
        private global::System.String _img_loc;
        partial void Onimg_locChanging(global::System.String value);
        partial void Onimg_locChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("letsshopModel", "FK_orders_products", "order")]
        public EntityCollection<order> orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order>("letsshopModel.FK_orders_products", "order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order>("letsshopModel.FK_orders_products", "order", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="sub_category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sub_category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sub_category object.
        /// </summary>
        /// <param name="subcat_id">Initial value of the subcat_id property.</param>
        /// <param name="subcat_name">Initial value of the subcat_name property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        public static sub_category Createsub_category(global::System.Int32 subcat_id, global::System.String subcat_name, global::System.DateTime created_date)
        {
            sub_category sub_category = new sub_category();
            sub_category.subcat_id = subcat_id;
            sub_category.subcat_name = subcat_name;
            sub_category.created_date = created_date;
            return sub_category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 subcat_id
        {
            get
            {
                return _subcat_id;
            }
            set
            {
                if (_subcat_id != value)
                {
                    Onsubcat_idChanging(value);
                    ReportPropertyChanging("subcat_id");
                    _subcat_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("subcat_id");
                    Onsubcat_idChanged();
                }
            }
        }
        private global::System.Int32 _subcat_id;
        partial void Onsubcat_idChanging(global::System.Int32 value);
        partial void Onsubcat_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String subcat_name
        {
            get
            {
                return _subcat_name;
            }
            set
            {
                Onsubcat_nameChanging(value);
                ReportPropertyChanging("subcat_name");
                _subcat_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("subcat_name");
                Onsubcat_nameChanged();
            }
        }
        private global::System.String _subcat_name;
        partial void Onsubcat_nameChanging(global::System.String value);
        partial void Onsubcat_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="contact_Number">Initial value of the Contact_Number property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="date_of_birth">Initial value of the Date_of_birth property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="user_type">Initial value of the user_type property.</param>
        /// <param name="created_Date">Initial value of the Created_Date property.</param>
        public static user Createuser(global::System.Int32 user_id, global::System.String name, global::System.String email, global::System.String contact_Number, global::System.String gender, global::System.String address, global::System.String date_of_birth, global::System.String username, global::System.String password, global::System.String user_type, global::System.DateTime created_Date)
        {
            user user = new user();
            user.user_id = user_id;
            user.Name = name;
            user.Email = email;
            user.Contact_Number = contact_Number;
            user.Gender = gender;
            user.Address = address;
            user.Date_of_birth = date_of_birth;
            user.Username = username;
            user.Password = password;
            user.user_type = user_type;
            user.Created_Date = created_Date;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contact_Number
        {
            get
            {
                return _Contact_Number;
            }
            set
            {
                OnContact_NumberChanging(value);
                ReportPropertyChanging("Contact_Number");
                _Contact_Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contact_Number");
                OnContact_NumberChanged();
            }
        }
        private global::System.String _Contact_Number;
        partial void OnContact_NumberChanging(global::System.String value);
        partial void OnContact_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Date_of_birth
        {
            get
            {
                return _Date_of_birth;
            }
            set
            {
                OnDate_of_birthChanging(value);
                ReportPropertyChanging("Date_of_birth");
                _Date_of_birth = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Date_of_birth");
                OnDate_of_birthChanged();
            }
        }
        private global::System.String _Date_of_birth;
        partial void OnDate_of_birthChanging(global::System.String value);
        partial void OnDate_of_birthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_type
        {
            get
            {
                return _user_type;
            }
            set
            {
                Onuser_typeChanging(value);
                ReportPropertyChanging("user_type");
                _user_type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_type");
                Onuser_typeChanged();
            }
        }
        private global::System.String _user_type;
        partial void Onuser_typeChanging(global::System.String value);
        partial void Onuser_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created_Date
        {
            get
            {
                return _Created_Date;
            }
            set
            {
                OnCreated_DateChanging(value);
                ReportPropertyChanging("Created_Date");
                _Created_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created_Date");
                OnCreated_DateChanged();
            }
        }
        private global::System.DateTime _Created_Date;
        partial void OnCreated_DateChanging(global::System.DateTime value);
        partial void OnCreated_DateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="letsshopModel", Name="view")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class view : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new view object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="product_Name">Initial value of the Product_Name property.</param>
        public static view Createview(global::System.Int32 id, global::System.String product_Name)
        {
            view view = new view();
            view.Id = id;
            view.Product_Name = product_Name;
            return view;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Product_id
        {
            get
            {
                return _Product_id;
            }
            set
            {
                OnProduct_idChanging(value);
                ReportPropertyChanging("Product_id");
                _Product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_id");
                OnProduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Product_id;
        partial void OnProduct_idChanging(Nullable<global::System.Int32> value);
        partial void OnProduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Hits
        {
            get
            {
                return _Hits;
            }
            set
            {
                OnHitsChanging(value);
                ReportPropertyChanging("Hits");
                _Hits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hits");
                OnHitsChanged();
            }
        }
        private Nullable<global::System.Int32> _Hits;
        partial void OnHitsChanging(Nullable<global::System.Int32> value);
        partial void OnHitsChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="letsshopModel", Name="sptotal_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sptotal_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sptotal_Result object.
        /// </summary>
        /// <param name="customer_name">Initial value of the customer_name property.</param>
        public static sptotal_Result Createsptotal_Result(global::System.String customer_name)
        {
            sptotal_Result sptotal_Result = new sptotal_Result();
            sptotal_Result.customer_name = customer_name;
            return sptotal_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String customer_name
        {
            get
            {
                return _customer_name;
            }
            set
            {
                Oncustomer_nameChanging(value);
                ReportPropertyChanging("customer_name");
                _customer_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("customer_name");
                Oncustomer_nameChanged();
            }
        }
        private global::System.String _customer_name;
        partial void Oncustomer_nameChanging(global::System.String value);
        partial void Oncustomer_nameChanged();

        #endregion

    }

    #endregion

    
}
